# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Location.destroy_all
List.destroy_all
Favorite.destroy_all

locations = Location.create([
  { name: 'ABC Cocina', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'al Bustan', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Alobar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Andy\'s Seafood & Grill', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Ápizz', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Aroma Kitchen & Wine Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'August', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Ayada', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Baci & Abbracci', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Basil Brick Oven Pizza', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Battersby', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Beyoglu', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Bianca', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Bistro 33', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Bohemian', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Boqueria', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Bread & Tulips', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'bún-ker', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Buttermilk Channel', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Casa Enríque', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Cata', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Char No. 4', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Chavela’s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Cho Dang Gol', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Ciccio', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Clinton St. Baking Company', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Congee Village', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Crispo', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Cô Ba', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'DBGB Kitchen & Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Dear Bushwick', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Dim Sum Go Go', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Diner', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Dirt Candy', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Do or Dine', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Don Antonio by Starita', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Ed\'s Lobster Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Egg', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'El Parador', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'El Paso Taqueria', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Enoteca Maria', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Family Recipe', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Fatty Crab', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Fatty ‘Cue', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Frankies 457 Spuntino', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Franny\'s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Garden Court Café', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'General Greene (The)', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Gennaro', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Good Fork (The)', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Gran Eléctrica', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'HanGawi', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Havana Café', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Hecho en Dumbo', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Hill Country Chicken', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Hino Maru Ramen', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Hunan House', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Hunan Kitchen of Grand Sichuan', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Il Buco Alimentari & Vineria', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Il Poeta', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'J.G. Melon', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Jean Claude', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'John Brown Smokehouse', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'J. Restaurant Chez Asta', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Jin Ramen', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Katz\'s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Kesté Pizza & Vino', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'L\'Ecole', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Land of Plenty', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Laut', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Lil\' Frankie\'s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Little Pepper', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Lu Xiang Yuan', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Lupa', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mamak House', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mapo Tofu', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Marlow & Sons', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mayfield', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Meatball Shop (The)', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mercato', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mesa Coyoacán', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mexicana Mama', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mexicosina', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Mile End', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Miss Mamie\'s Spoonbread Too', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Momofuku Noodle Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Momofuku Ssäm Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Momokawa', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Murray\'s Cheese Bar', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'New Malaysia', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Northeast Kingdom', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'No. 7', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Northern Spy Food Co.', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Nyonya', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Ornella', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Paulie Gee’s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Perry Street', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Phoenix Garden', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Pok Pok NY', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Porsena', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Prime Meats', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Prospect', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Prune', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Purple Yam', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Robataya', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Roberta\'s', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Rubirosa', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Runner & Stone', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Rye', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Salt & Fat', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Saravanaas', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Seersucker', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Seo', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Sip Sak', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Snack', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Soba-Ya', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Speedy Romeo', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Supper', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Sura', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Szechuan Gourmet', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Tang', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Tanoreen', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Tertulia', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Tra Di Noi', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Traif', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Turkish Kitchen', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Uncle Zhou', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Untitled', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Uva', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Vida', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Vinegar Hill House', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Wild Edibles', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Xixa', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Yunnan Kitchen', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Zabb Elee (East Village)', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Zabb Elee (Queens)', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'zero otto nove', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Zoma', michelinrate: 0, city: 'New York, NY' }, 
  { name: 'Chef\'s Table at Brooklyn Fare', michelinrate: 3, city: 'New York, NY', url: 'https://d19weqihs4yh5u.cloudfront.net/links/3e89919e08de7f49f23f44d090f4388941acf8f4/350x200' }, 
  { name: 'Daniel', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'Eleven Madison Park', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'Jean Georges', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'Le Bernardin', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'Masa', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'Per Se', michelinrate: 3, city: 'New York, NY' }, 
  { name: 'atera', michelinrate: 2, city: 'New York, NY' }, 
  { name: 'Jungsik', michelinrate: 2, city: 'New York, NY' }, 
  { name: 'Marea', michelinrate: 2, city: 'New York, NY' }, 
  { name: 'Momofuku Ko', michelinrate: 2, city: 'New York, NY' }, 
  { name: 'Soto', michelinrate: 2, city: 'New York, NY' }, 
  { name: 'Ai Fiori', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Aldea', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'annisa', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Aquavit', michelinrate: 1, city: 'New York, NY', url: 'https://d19weqihs4yh5u.cloudfront.net/links/3e89919e08de7f49f23f44d090f4388941acf8f4/350x200' }, 
  { name: 'Aska', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Aureole', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'A Voce Columbus', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'A Voce Madison', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Babbo', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Blanca', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Blue Hill', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Bouley', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Breslin (The)', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Brushstroke', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Café Boulud', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Café China', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Carbone', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Casa Mono', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Caviar Russe', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Danji', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Danny Brown Wine Bar & Kitchen', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Del Posto', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Dovetail', michelinrate: 1, city: 'New York, NY' }, 
  { name: '15 East', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Gotham Bar and Grill', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Gramercy Tavern', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Hakkasan', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Ichimura', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Jewel Bako', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Junoon', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Kajitsu', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Kyo Ya', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Lan Sheng', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Le Restaurant', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Lincoln', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Minetta Tavern', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Modern (The)', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Musket Room (The)', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'NoMad', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Oceana', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Peter Luger', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Public', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Rosanjin', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Rouge Tomate', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Seäsonal', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Spotted Pig', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Sushi Azabu', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Sushi of Gari', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Tamarind Tribeca', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Telepan', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Tori Shin', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Torrisi Italian Specialties', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Tulsi', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'Wallsé', michelinrate: 1, city: 'New York, NY' }, 
  { name: 'wd~50', michelinrate: 1, city: 'New York, NY' }
  ])

to_visit, guilty, tried_true = List.create([
  { name: 'To Visit' , user_id: 1 }, 
  { name: 'Guilty Pleasures', user_id: 1 },
  { name: 'Tried and True', user_id: 1 }
])

to_visit.locations = [locations[15], locations[101], locations[54]]
guilty.locations = [locations[150], locations[101], locations[106], locations[84]]
tried_true.locations = [locations[15], locations[27], locations[143], locations[7]]